version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world test.

      - run:
          name: Print the Current Time
          command: date

      - run:
          name: Apt update 
          command: apt-get update

      - run:
          name: Fix sudo 
          command: apt-get install sudo

      - run:
          name: Apt install
          command: sudo apt-get install -y build-essential make git gcc

      - run:
          name: Build
          command: make
