version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date

      - run:
          name: apt install
          command: sudo env PATH=$PATH apt-get install -y build-essential make git gcc

      - run:
          name: Build
          command: make
