version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date

      - run:
          name: fix sudo
          command: alias sudo='sudo env PATH=$PATH'

      - run:
          name: apt install
          command: sudo apt-get install -y build-essential make git gcc

      - run:
          name: Build
          command: make
